events {}

http {
    server {
        listen 80;

        location /api/tickets/ {
            proxy_pass http://ticket_service:8000/;
        }

        location /api/agents/ {
            proxy_pass http://agent_service:8000/;
        }
    }
}