@startuml
skinparam maxMessageSize 150
autonumber

actor "Клиент" as Client
participant "Web UI" as UI
participant "Ticket API" as API
participant "Router Service" as Router
database "PostgreSQL\n(БД)" as DB
participant "Message Broker\n(RabbitMQ)" as Broker

Client -> UI: Заполняет форму (Тема, Описание, Категория)
UI -> API: POST /api/tickets\nHeaders: Idempotency-Key
activate API

API -> DB: BEGIN TRANSACTION
API -> DB: INSERT INTO tickets (status: NEW)
DB --> API: ticket_id = "HD-404"

note over API, Router: Попытка определить очередь
API -> Router: GET /route?category_id=5
activate Router
Router -[#red]->x API: Timeout (нет ответа > 2 сек)
deactivate Router

note right of API: Срабатывает Circuit Breaker.\nПрименяется Fallback-стратегия:\nqueue_id = "Default" 

API -> DB: UPDATE tickets SET queue_id = "Default"
API -> DB: COMMIT TRANSACTION

API -[#blue]> Broker:[Async] Publish Event "TicketCreated" (HD-404)
activate Broker
Broker --[#blue]> API: ACK
deactivate Broker

API --> UI: 201 Created (ticket_id: "HD-404")
note right: Для клиента процесс успешен,\nнесмотря на сбой маршрутизации
deactivate API

UI --> Client: Показать: "Тикет #HD-404 успешно создан"

@enduml