# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ticket_pb2 as ticket__pb2


class TicketServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateTicket = channel.unary_unary(
        '/ticket.TicketService/CreateTicket',
        request_serializer=ticket__pb2.CreateTicketRequest.SerializeToString,
        response_deserializer=ticket__pb2.TicketResponse.FromString,
        )
    self.GetTicket = channel.unary_unary(
        '/ticket.TicketService/GetTicket',
        request_serializer=ticket__pb2.GetTicketRequest.SerializeToString,
        response_deserializer=ticket__pb2.TicketResponse.FromString,
        )
    self.StreamTickets = channel.unary_stream(
        '/ticket.TicketService/StreamTickets',
        request_serializer=ticket__pb2.StreamRequest.SerializeToString,
        response_deserializer=ticket__pb2.TicketResponse.FromString,
        )


class TicketServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateTicket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTicket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamTickets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TicketServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateTicket': grpc.unary_unary_rpc_method_handler(
          servicer.CreateTicket,
          request_deserializer=ticket__pb2.CreateTicketRequest.FromString,
          response_serializer=ticket__pb2.TicketResponse.SerializeToString,
      ),
      'GetTicket': grpc.unary_unary_rpc_method_handler(
          servicer.GetTicket,
          request_deserializer=ticket__pb2.GetTicketRequest.FromString,
          response_serializer=ticket__pb2.TicketResponse.SerializeToString,
      ),
      'StreamTickets': grpc.unary_stream_rpc_method_handler(
          servicer.StreamTickets,
          request_deserializer=ticket__pb2.StreamRequest.FromString,
          response_serializer=ticket__pb2.TicketResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ticket.TicketService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
