# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ticket.proto',
  package='ticket',
  syntax='proto3',
  serialized_pb=_b('\n\x0cticket.proto\x12\x06ticket\"K\n\x13\x43reateTicketRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\t\"%\n\x10GetTicketRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\"!\n\rStreamRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"D\n\x0eTicketResponse\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t2\xd5\x01\n\rTicketService\x12\x43\n\x0c\x43reateTicket\x12\x1b.ticket.CreateTicketRequest\x1a\x16.ticket.TicketResponse\x12=\n\tGetTicket\x12\x18.ticket.GetTicketRequest\x1a\x16.ticket.TicketResponse\x12@\n\rStreamTickets\x12\x15.ticket.StreamRequest\x1a\x16.ticket.TicketResponse0\x01\x62\x06proto3')
)




_CREATETICKETREQUEST = _descriptor.Descriptor(
  name='CreateTicketRequest',
  full_name='ticket.CreateTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='ticket.CreateTicketRequest.client_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='ticket.CreateTicketRequest.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='ticket.CreateTicketRequest.priority', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=99,
)


_GETTICKETREQUEST = _descriptor.Descriptor(
  name='GetTicketRequest',
  full_name='ticket.GetTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='ticket.GetTicketRequest.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=138,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='ticket.StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='ticket.StreamRequest.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=173,
)


_TICKETRESPONSE = _descriptor.Descriptor(
  name='TicketResponse',
  full_name='ticket.TicketResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='ticket.TicketResponse.ticket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ticket.TicketResponse.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='ticket.TicketResponse.subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=243,
)

DESCRIPTOR.message_types_by_name['CreateTicketRequest'] = _CREATETICKETREQUEST
DESCRIPTOR.message_types_by_name['GetTicketRequest'] = _GETTICKETREQUEST
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
DESCRIPTOR.message_types_by_name['TicketResponse'] = _TICKETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateTicketRequest = _reflection.GeneratedProtocolMessageType('CreateTicketRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATETICKETREQUEST,
  __module__ = 'ticket_pb2'
  # @@protoc_insertion_point(class_scope:ticket.CreateTicketRequest)
  ))
_sym_db.RegisterMessage(CreateTicketRequest)

GetTicketRequest = _reflection.GeneratedProtocolMessageType('GetTicketRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTICKETREQUEST,
  __module__ = 'ticket_pb2'
  # @@protoc_insertion_point(class_scope:ticket.GetTicketRequest)
  ))
_sym_db.RegisterMessage(GetTicketRequest)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _STREAMREQUEST,
  __module__ = 'ticket_pb2'
  # @@protoc_insertion_point(class_scope:ticket.StreamRequest)
  ))
_sym_db.RegisterMessage(StreamRequest)

TicketResponse = _reflection.GeneratedProtocolMessageType('TicketResponse', (_message.Message,), dict(
  DESCRIPTOR = _TICKETRESPONSE,
  __module__ = 'ticket_pb2'
  # @@protoc_insertion_point(class_scope:ticket.TicketResponse)
  ))
_sym_db.RegisterMessage(TicketResponse)



_TICKETSERVICE = _descriptor.ServiceDescriptor(
  name='TicketService',
  full_name='ticket.TicketService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=246,
  serialized_end=459,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTicket',
    full_name='ticket.TicketService.CreateTicket',
    index=0,
    containing_service=None,
    input_type=_CREATETICKETREQUEST,
    output_type=_TICKETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTicket',
    full_name='ticket.TicketService.GetTicket',
    index=1,
    containing_service=None,
    input_type=_GETTICKETREQUEST,
    output_type=_TICKETRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamTickets',
    full_name='ticket.TicketService.StreamTickets',
    index=2,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_TICKETRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TICKETSERVICE)

DESCRIPTOR.services_by_name['TicketService'] = _TICKETSERVICE

# @@protoc_insertion_point(module_scope)
